---
title: "Main Processing File"
author: "Kuiyuan Shao"
date: "31/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Sourcing the R scripts
```{r}
source("randomPopu.R")
source("multistageSamp.R")
source("pmatrixSim.R")
source("plotFuns.R")
```

### Survey Design 1 (First Population)

```{r, warning = F}
#set.seed(2021)
#population1 <- random_population(1e7, mean = 40)
#save(population1, file = "popu.RData")
```

# 35, 100 = 25
# 40, 125 = 30
```{r }
#load(popu.RData)
sample1.1 <- sampling(population1, ncluster1 = 35, ncluster2 = 100, cluster_observ = 200)
strat_design1.1 <- svydesign(id = ~ cluster1 + cluster2 + ID_unit, strata = ~ strata, 
                             data = sample1.1, weights = ~ pw)
strat_design1.1
degf(strat_design1.1)
```

#### One Testing Term
```{r, fig.width = 12, fig.height = 7}
options(future.globals.maxSize= 10485760000)
#Poisson with 25 degf
pmatrix_1_1 <- pmatrix_generator(population1, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "poisson")
exp_pmatrix_1_1 <- exp_p(pmatrix_1_1)
#Poisson with 30 degf
pmatrix_1_2 <- pmatrix_generator(population1, ncluster1 = 40, ncluster2 = 125, 
                                 cluster_observ = 160, iteration = 200, regression = "poisson")
exp_pmatrix_1_2 <- exp_p(pmatrix_1_2)
#Linear with 25 degf
pmatrix_1_3 <- pmatrix_generator(population1, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "linear")
exp_pmatrix_1_3 <- exp_p(pmatrix_1_3)
#Linear with 30 degf
pmatrix_1_4 <- pmatrix_generator(population1, ncluster1 = 40, ncluster2 = 125, 
                                 cluster_observ = 160, iteration = 200, regression = "linear")
exp_pmatrix_1_4 <- exp_p(pmatrix_1_4)
#Binomial with 25 degf
pmatrix_1_5 <- pmatrix_generator(population1, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "binomial")
exp_pmatrix_1_5 <- exp_p(pmatrix_1_5)
#Binomial with 30 degf
pmatrix_1_6 <- pmatrix_generator(population1, ncluster1 = 40, ncluster2 = 125, 
                                 cluster_observ = 160, iteration = 200, regression = "binomial")
exp_pmatrix_1_6 <- exp_p(pmatrix_1_6)
plotfun(exp_pmatrix_1_1, pmatrix_1_1, exp_pmatrix_1_2, pmatrix_1_2)
plotfun(exp_pmatrix_1_3, pmatrix_1_3, exp_pmatrix_1_4, pmatrix_1_4)
plotfun(exp_pmatrix_1_5, pmatrix_1_5, exp_pmatrix_1_6, pmatrix_1_6)
```

#### Four Testing Terms
```{r}
#Poisson with 25 degf
pmatrix_1_7 <- pmatrix_generator(population1, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "poisson", term = Inf)
exp_pmatrix_1_7 <- exp_p(pmatrix_1_7)
#Poisson with 30 degf
pmatrix_1_8 <- pmatrix_generator(population1, ncluster1 = 40, ncluster2 = 125, 
                                 cluster_observ = 160, iteration = 200, regression = "poisson", term = Inf)
exp_pmatrix_1_8 <- exp_p(pmatrix_1_8)
#Linear with 25 degf
pmatrix_1_9 <- pmatrix_generator(population1, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "linear", term = Inf)
exp_pmatrix_1_9 <- exp_p(pmatrix_1_9)
#Linear with 30 degf
pmatrix_1_10 <- pmatrix_generator(population1, ncluster1 = 40, ncluster2 = 125, 
                                  cluster_observ = 160, iteration = 200, regression = "linear", term = Inf)
exp_pmatrix_1_10 <- exp_p(pmatrix_1_10)
#Binomial with 25 degf
pmatrix_1_11 <- pmatrix_generator(population1, ncluster1 = 35, ncluster2 = 100, 
                                  cluster_observ = 200, iteration = 200, regression = "binomial", term = Inf)
exp_pmatrix_1_11 <- exp_p(pmatrix_1_11)
#Binomial with 30 degf
pmatrix_1_12 <- pmatrix_generator(population1, ncluster1 = 40, ncluster2 = 125, 
                                  cluster_observ = 160, iteration = 200, regression = "binomial", term = Inf)
exp_pmatrix_1_12 <- exp_p(pmatrix_1_12)
plotfun(exp_pmatrix_1_7, pmatrix_1_7, exp_pmatrix_1_8, pmatrix_1_8)
plotfun(exp_pmatrix_1_9, pmatrix_1_9, exp_pmatrix_1_10, pmatrix_1_10)
plotfun(exp_pmatrix_1_11, pmatrix_1_11, exp_pmatrix_1_12, pmatrix_1_12)
```

### Survery Design 2 (Second Population)
```{r, warning = F}
set.seed(2022)
population2 <- random_population(mean = 0)
```

```{r}
sample2.1 <- sampling(population2, ncluster1 = 35, ncluster2 = 100, cluster_observ = 200)
strat_design2.1 <- svydesign(id = ~ cluster1 + cluster2 + personID, strata = ~ strata, data = sample2.1,
                             weights = ~ pw)
strat_design2.1
degf(strat_design2.1)

sample2.2 <- sampling(population2, ncluster1 = 40, ncluster2 = 125, cluster_observ = 160)
strat_design2.2 <- svydesign(id = ~ cluster1 + cluster2 + personID, strata = ~ strata, data = sample2.2, 
                             weights = ~ pw)
strat_design2.2
degf(strat_design2.2)

svymean(~out1, strat_design2.2)
svymean(~out2, strat_design2.2)
#tbl <- svytable(~out2 + test1, design = strat_design2.1)
#tbl[] <- paste0(round(tbl, 2), " (", round(prop.table(tbl)*100, 2), "%)")
#tbl
#ggplot(sample2.1, aes(x = test1, y = out1)) + geom_violin(scale = "count") + xlab("Exposure") + ylab("Outcome V1")
```

#### One Testing Term
```{r, fig.width = 12, fig.height = 7}
#Poisson with 25 degf
pmatrix_2_1 <- pmatrix_generator(population2, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "poisson")
exp_pmatrix_2_1 <- exp_p(pmatrix_2_1)
#Poisson with 30 degf
pmatrix_2_2 <- pmatrix_generator(population2, ncluster1 = 40, ncluster2 = 125, 
                                 cluster_observ = 160, iteration = 200, regression = "poisson")
exp_pmatrix_2_2 <- exp_p(pmatrix_2_2)
#Linear with 25 degf
pmatrix_2_3 <- pmatrix_generator(population2, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "linear")
exp_pmatrix_2_3 <- exp_p(pmatrix_2_3)
#Linear with 30 degf
pmatrix_2_4 <- pmatrix_generator(population2, ncluster1 = 40, ncluster2 = 125, 
                                 cluster_observ = 160, iteration = 200, regression = "linear")
exp_pmatrix_2_4 <- exp_p(pmatrix_2_4)
#Binomial with 25 degf
pmatrix_2_5 <- pmatrix_generator(population2, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "binomial")
exp_pmatrix_2_5 <- exp_p(pmatrix_2_5)
#Binomial with 30 degf
pmatrix_2_6 <- pmatrix_generator(population2, ncluster1 = 40, ncluster2 = 125, 
                                 cluster_observ = 160, iteration = 200, regression = "binomial")
exp_pmatrix_2_6 <- exp_p(pmatrix_2_6)
plotfun(exp_pmatrix_2_1, pmatrix_2_1, exp_pmatrix_2_2, pmatrix_2_2)
plotfun(exp_pmatrix_2_3, pmatrix_2_3, exp_pmatrix_2_4, pmatrix_2_4)
plotfun(exp_pmatrix_2_5, pmatrix_2_5, exp_pmatrix_2_6, pmatrix_2_6)
```

#### Four Testing Terms
```{r}
#Poisson with 25 degf
pmatrix_2_7 <- pmatrix_generator(population2, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "poisson", term = Inf)
exp_pmatrix_2_7 <- exp_p(pmatrix_2_7)
#Poisson with 30 degf
pmatrix_2_8 <- pmatrix_generator(population2, ncluster1 = 40, ncluster2 = 125, 
                                 cluster_observ = 160, iteration = 200, regression = "poisson", term = Inf)
exp_pmatrix_2_8 <- exp_p(pmatrix_2_8)
#Linear with 25 degf
pmatrix_2_9 <- pmatrix_generator(population2, ncluster1 = 35, ncluster2 = 100, 
                                 cluster_observ = 200, iteration = 200, regression = "linear", term = Inf)
exp_pmatrix_2_9 <- exp_p(pmatrix_2_9)
#Linear with 30 degf
pmatrix_2_10 <- pmatrix_generator(population2, ncluster1 = 40, ncluster2 = 125, 
                                  cluster_observ = 160, iteration = 200, regression = "linear", term = Inf)
exp_pmatrix_2_10 <- exp_p(pmatrix_2_10)
#Binomial with 25 degf
pmatrix_2_11 <- pmatrix_generator(population2, ncluster1 = 35, ncluster2 = 100, 
                                  cluster_observ = 200, iteration = 200, regression = "binomial", term = Inf)
exp_pmatrix_2_11 <- exp_p(pmatrix_2_11)
#Binomial with 30 degf
pmatrix_2_12 <- pmatrix_generator(population2, ncluster1 = 40, ncluster2 = 125, 
                                  cluster_observ = 160, iteration = 200, regression = "binomial", term = Inf)
exp_pmatrix_2_12 <- exp_p(pmatrix_2_12)
plotfun(exp_pmatrix_2_7, pmatrix_2_7, exp_pmatrix_2_8, pmatrix_2_8)
plotfun(exp_pmatrix_2_9, pmatrix_2_9, exp_pmatrix_2_10, pmatrix_2_10)
plotfun(exp_pmatrix_2_11, pmatrix_2_11, exp_pmatrix_2_12, pmatrix_2_12)
```